# TODO check hidden-dim, num-layer clip-init
# Basic setup # args from train_PrefPPO
seed : 1
n_steps : 400
lr : 0.0003
total_timesteps : 2500000
batch_size : 64
ent_coef : 0.01
hidden_dim : 64
num_layer : 2
use_sde : False
sde_freq : -1
experiment: ppo_reward
gae_lambda : 0.95
n_epochs : 10
normalize : 1
n_envs : 16

# reward_model
re_lr : 0.0003
re_segment : 50
re_act : tanh
re_num_interaction : 16000
re_num_feed : 1
re_batch : 128
re_update : 100
re_feed_type : 1
re_large_batch : 10
re_max_feed : 10000
teacher_beta : 1
teacher_gamma : 1
teacher_eps_mistake : 0
teacher_eps_skip : 0
teacher_eps_equal : 0
max_ep_len : 1000